geekganization/MOUP

- Routory/Routory/Presentation/MyPage/View/InfoView.swift
- Routory/Routory/Presentation/MyPage/View/MyPageMenuListView.swift
- Routory/Routory/Presentation/MyPage/View/MyPageNavigationBar.swift
- Routory/Routory/Presentation/MyPage/View/MyPageTableViewCell.swift
- Routory/Routory/Presentation/MyPage/View/MyPageView.swift
- Routory/Routory/Presentation/MyPage/ViewController/InfoViewController.swift
- Routory/Routory/Presentation/MyPage/ViewController/MyPageViewController.swift
- Routory/Routory/Resources/Assets.xcassets/Icons/Chevron/BackButton.imageset/BackButton.svg
- Routory/Routory/Resources/Assets.xcassets/Icons/Chevron/BackButton.imageset/Contents.json
- Routory/Routory/Resources/Assets.xcassets/Icons/Chevron/ChevronRight.imageset/ChevronRight.svg
- Routory/Routory/Resources/Assets.xcassets/Icons/Chevron/ChevronRight.imageset/Contents.json
- #4 
</br>
**마이페이지 UI 구현**
- 프로필 이미지, 이름, 역할을 포함한 상단 프로필 영역 추가
- 4개의 고정 메뉴를 보여주는 메뉴 리스트 구성 (UITableView)
- 로그아웃 버튼 추가
- SnapKit + Then 기반으로 UI 구성
**사용자 정보 처리**
- DummyUser 구조체를 통해 더미 사용자 데이터 구성
- MyPageView.update(user:) 메서드를 통해 프로필 정보 업데이트 가능하도록 구현
**정보(Info) 화면 추가**
- InfoView, InfoViewController 신규 구현
- InfoMenu enum을 기반으로 구성
- 커스텀 내비게이션 바 MyPageNavigationBar 추가
- Back 버튼 SVG 추가 및 Assets 등록
</br>
| 마이페이지 | <img src = "https://github.com/user-attachments/assets/b1ef3e3b-1f91-415d-93d9-d96ebea02c1e" width ="250"> |
| 정보 메뉴 화면 | <img src = "https://github.com/user-attachments/assets/8419e680-7e91-4872-a4f6-0c3b56102eac" width ="250"> |
</br>
코딩 컨벤션에 익숙치 않아서 혹시 맞지 않는 부분 짚어주시면 반영하겠습니다. 손 가는대로 코딩하다보니 난잡합니다. 가독성과 유지보수성을 높이는 방안 …
> 마이페이지 UI 구현 완료

- Routory/Routory/Presentation/Registration/Components/SelectionViewController.swift
- Routory/Routory/Presentation/Registration/Components/TextInputViewController.swift
- Routory/Routory/Presentation/Registration/ShiftRegistration/Submodules/ColorSelection/ViewController/ColorSelectionViewController.swift
- Routory/Routory/Presentation/Registration/ShiftRegistration/Submodules/EmployeeSelection /ViewController/EmployeeSelectionViewController.swift
- Routory/Routory/Presentation/Registration/ShiftRegistration/Submodules/NewRoutine/ViewController/NewRoutineViewController.swift
- Routory/Routory/Presentation/Registration/ShiftRegistration/Submodules/RepeatDays/ViewController/RepeatDaysViewController.swift
- Routory/Routory/Presentation/Registration/ShiftRegistration/Submodules/RoutineSelection/ViewController/RoutineSelectionViewController.swift
- Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/OwnerShiftRegistrationViewController.swift
- Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/WorkShiftRegistrationViewController.swift
- Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/OwnerWorkplaceRegistrationViewController.swift
- Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/WorkerWorkplaceRegistrationViewController.swift
- #48 
</br>
- 스와이프 안되는 문제 해결
</br>
</br>
> feat: #48 - 스와이프 안되는 문제 해결

- Routory/Routory.xcodeproj/project.pbxproj
- Routory/Routory/App/SceneDelegate.swift
- Routory/Routory/Common/Managers/UserManager.swift
- Routory/Routory/Presentation/Home/ViewController/HomeViewController.swift
- Routory/Routory/Presentation/Home/ViewModel/HomeViewModel.swift
- Routory/Routory/Presentation/Login/View/LoginViewController.swift
- Routory/Routory/Presentation/MyPage/ViewController/MyPageViewController.swift
- Routory/Routory/Presentation/MyPage/ViewModel/MyPageViewModel.swift
- Routory/Routory/Presentation/Routine/ViewController/ManageRoutineViewController.swift
- Routory/Routory/Presentation/Routine/ViewController/WorkplaceRoutineViewController.swift
- Routory/Routory/Presentation/Routine/ViewModel/ManageRoutineViewModel.swift
- Routory/Routory/Presentation/Signup/View/SignupViewController.swift
- Routory/Routory/Presentation/Tabbar/ViewController/TabBarViewModel.swift
- Routory/Routory/Presentation/Tabbar/ViewController/TabbarViewController.swift
- #52 
</br>
- UserManager 구현
- TabBarViewModel 구현 및 관련 파일 코드 정리 
</br>
> 탭바 뷰모델 구현 및 전체 루틴 관리 데이터 fetch 구현

- Routory/Routory/Data/Repositories/EventRepository.swift
- Routory/Routory/Data/Repositories/Repository.swift
- Routory/Routory/Data/Services/EventService.swift
- Routory/Routory/Domain/Entities/Entity.swift
- Routory/Routory/Domain/Interfaces/Repositories/EventRepositoryProtocol.swift
- Routory/Routory/Domain/Interfaces/Repositories/RepositoryProtocol.swift
- Routory/Routory/Domain/Interfaces/UseCases/EventUsecaseProtocol.swift
- Routory/Routory/Domain/Interfaces/UseCases/UseCaseProtocol.swift
- Routory/Routory/Domain/UseCases/EventUseCase.swift
- Routory/Routory/Domain/UseCases/UseCase.swift
- #55 
</br>
- 캘린더 이벤트 월별 / 일별 조회 구현
- 유즈케이스에 day가 null이면 월별 조회 -> day가 null이 아니면 일별 조회입니다.
> 이벤트 일별 / 월별 조회

- Routory/Routory/Presentation/Components/BaseNavigationBar.swift
- Routory/Routory/Presentation/Home/View/HomeView.swift
- Routory/Routory/Presentation/Home/ViewController/HomeViewController.swift
- Routory/Routory/Presentation/Home/ViewController/WorkplaceAddModalViewController.swift
- Routory/Routory/Presentation/Home/ViewModel/HomeViewModel.swift
- Routory/Routory/Presentation/Routine/View/Cell/TodaysRoutineCell.swift
- Routory/Routory/Presentation/Routine/View/WorkplaceRoutineView.swift
- Routory/Routory/Presentation/Routine/ViewController/ManageRoutineViewController.swift
> 홈 내 미완성 기능 일부 구현

- Routory/Routory/Data/Repositories/CalendarRepository.swift
- Routory/Routory/Data/Repositories/WorkplaceRepository.swift
- Routory/Routory/Data/Services/CalendarService.swift
- Routory/Routory/Data/Services/WorkplaceService.swift
- Routory/Routory/Domain/Interfaces/Repositories/CalendarRepositoryProtocol.swift
- Routory/Routory/Domain/Interfaces/Repositories/WorkplaceRepositoryProtocol.swift
- Routory/Routory/Domain/Interfaces/UseCases/CalendarUseCaseProtocol.swift
- Routory/Routory/Domain/Interfaces/UseCases/WorkplaceUseCaseProtocol.swift
- Routory/Routory/Domain/UseCases/CalendarUseCase.swift
- Routory/Routory/Domain/UseCases/WorkplaceUseCase.swift
- #55 
</br>
- 신규 근무지 추가 로직 구현
- 근무 ( 이벤트 ) 추가 로직 구현
> 신규 근무지 추가 / 근무(이벤트) 추가 로직 구현

- Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/WorkerWorkplaceRegistrationViewController.swift
> feat: #70 - workConditionView랑 labelView 숨김처리

- Routory/Routory.xcodeproj/project.pbxproj
- Routory/Routory/Common/Utils/InviteCodeGenerator.swift
- Routory/Routory/Resources/JSON/opensource_license.json
Github Issue: #68
- #68 
</br>
- 사용 방법: 원하는 위치에 다음 코드를 추가하세요:
```swift
let uid = 파이어베이스에서 가져온 uid
let inviteCode = InviteCodeGenerator.generate(userID: uid)
print("inviteCode: \(inviteCode)")
// 실행 결과:
// inviteCode: EMAC3K
``` 
</br>
> 초대 코드 생성기 추가

- Routory/Routory/Data/Services/WorkplaceService.swift
- Routory/Routory/Domain/Entities/Dummy/DummyStoreInfo.swift
- Routory/Routory/Presentation/Home/View/Cell/MyStoreCell.swift
- Routory/Routory/Presentation/Home/View/Section/HomeTableViewFirstSection.swift
- Routory/Routory/Presentation/Home/ViewController/HomeViewController.swift
- Routory/Routory/Presentation/Home/ViewModel/HomeViewModel.swift
> 임시 목데이터를 이용해 사장님 매장 셀 testable하게 추가

- Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/OwnerShiftRegistrationViewController.swift
- Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/WorkShiftRegistrationViewController.swift
> feat: #83 - createdBy 코드 부분 수정

- Routory/Routory/Data/Repositories/WorkplaceRepository.swift
- Routory/Routory/Data/Services/UserService.swift
- Routory/Routory/Data/Services/WorkplaceService.swift
- Routory/Routory/Domain/Entities/Workplace.swift
- Routory/Routory/Domain/Interfaces/Repositories/WorkplaceRepositoryProtocol.swift
- Routory/Routory/Domain/Interfaces/UseCases/WorkplaceUseCaseProtocol.swift
- Routory/Routory/Domain/UseCases/WorkplaceUseCase.swift
- Routory/Routory/Presentation/MyPage/ViewController/DeleteAccountModalViewController.swift
> 근무지 삭제/ 고정급여 반환 / 회원탈퇴 로직 수정 / 월급일 반환 로직 구현 

- Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/WorkerWorkplaceRegistrationViewController.swift
> feat: #89 - 시급 안올라가는 문제 해결

- Routory/Routory/Presentation/Registration/ShiftRegistration/Submodules/NewRoutine/ViewController/NewRoutineViewController.swift
> fix: #105 - 테이블뷰 삭제 오류 해결

- Routory/Routory/Presentation/Home/View/ShareInviteCodeView.swift
- Routory/Routory/Presentation/Home/ViewController/InviteCodeViewController.swift
- Routory/Routory/Presentation/Home/ViewController/ShareInviteCodeViewController.swift
- Routory/Routory/Presentation/Home/ViewController/WorkplaceAddModalViewController.swift
- Routory/Routory/Presentation/MyPage/View/DeleteAccountModal.swift
- Routory/Routory/Presentation/MyPage/ViewController/AccountViewController.swift
- Routory/Routory/Presentation/MyPage/ViewController/DeleteAccountFailModalViewController.swift
- Routory/Routory/Presentation/MyPage/ViewController/DeleteAccountModalViewController.swift
- Routory/Routory/Presentation/MyPage/ViewController/MyPageViewController.swift
- Routory/Routory/Resources/Assets.xcassets/Icons/Home/CopyButton.imageset/Contents.json
- Routory/Routory/Resources/Assets.xcassets/Icons/Home/CopyButton.imageset/CopyButton.svg
- #99 #98 #97 
</br>
- 초대코드로 근무지 등록 모달에서 텍스트필드에 값이 비어있을 때 비활성화 처리했습니다.
- 구현한 모달에서 모달 외 영역을 터치하면 닫히도록 수정했습니다.
- 회원탈퇴 실패시 기존 alert에서 커스텀 모달 뷰로 구현했습니다.
> 초대 코드 조회하기 버튼 예외처리 외 기타 버그 수정

- Routory/Routory/Presentation/Calendar/View/Cell/CalendarDayCell.swift
- Routory/Routory/Presentation/Calendar/ViewController/CalendarViewController.swift
- Routory/Routory/Presentation/Calendar/ViewModel/CalendarViewModel.swift
- Routory/Routory/Presentation/Components/BaseNavigationBar.swift
- Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/OwnerShiftRegistrationViewController.swift
- Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/WorkShiftRegistrationViewController.swift
- #100 
</br>
- `CalendarViewController`가 `viewWillAppear`에서 API를 호출하도록 수정
- `CalendarEventListViewController` 모달이 다시 `present` 되는 시점 조정
</br>
| GIF | <img src = "https://github.com/user-attachments/assets/f2e5e9bc-1e0b-42a7-9dea-dcb9354255b3" width ="250"> |
</br>
> 근무 등록 화면 pop 관련 버그 수정

- Routory/Routory/Data/Services/CalendarService.swift
- Routory/Routory/Data/Services/EventService.swift
- Routory/Routory/Data/Services/RoutineService.swift
- Routory/Routory/Data/Services/WorkplaceService.swift
- Routory/Routory/Domain/Entities/CalendarEvent.swift
- Routory/Routory/Domain/Entities/Workplace.swift
Github issue #116
- #116 
</br>
- 리스너 방식 리펙토링
> refactor: 리스너 방식 리펙토링

- Routory/Routory/Presentation/Registration/WorkplaceRegistration/View/WorkplaceRegistrationContentView.swift
- Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/OwnerWorkplaceEditViewController.swift
- Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/OwnerWorkplaceRegistrationViewController.swift
- Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/WorkerWorkplaceRegistrationViewController.swift
> feat: #121 - 수정 모드에서만 알바생 관리 보이게 하기

- Routory/Routory/Domain/Entities/TodaysRoutine.swift
- Routory/Routory/Presentation/Home/View/Cell/MyStoreCell.swift
- Routory/Routory/Presentation/Home/View/Cell/MyWorkSpaceCell.swift
- Routory/Routory/Presentation/Home/View/HomeView.swift
- Routory/Routory/Presentation/Home/ViewController/HomeViewController.swift
- Routory/Routory/Presentation/Home/ViewModel/HomeViewModel.swift
- Routory/Routory/Presentation/Routine/View/Cell/TodaysRoutineCell.swift
- Routory/Routory/Presentation/Routine/ViewController/ManageRoutineViewController.swift
- Routory/Routory/Presentation/Routine/ViewController/WorkplaceRoutineViewController.swift
- Routory/Routory/Presentation/Routine/ViewModel/ManageRoutineViewModel.swift
- Routory/Routory/Presentation/Routine/ViewModel/WorkplaceRoutineViewModel.swift
- #54 
</br>
- 루틴 관리 페이지 내 데이터 바인딩
- 홈 진입 시 오늘의 루틴 개수 바인딩
</br>
| IMG | <img src = "https://github.com/user-attachments/assets/25fdf492-d7a9-4d5f-b073-954b8338c183" width ="250"> |
</br>
> 루틴 관리 페이지 및 홈 내 오늘의 루틴 데이터 바인딩

- Routory/Routory/Common/Utils/WageHelper.swift
- Routory/Routory/Data/Repositories/UserRepository.swift
- Routory/Routory/Data/Services/CalendarService.swift
- Routory/Routory/Data/Services/EventService.swift
- Routory/Routory/Data/Services/UserService.swift
- Routory/Routory/Data/Services/WorkplaceService.swift
- Routory/Routory/Domain/Interfaces/Repositories/UserRepositoryProtocol.swift
- Routory/Routory/Domain/Interfaces/UseCases/UserUseCaseProtocol.swift
- Routory/Routory/Domain/UseCases/UserUseCase.swift
- #140 
</br>
- 근무지 삭제 버그 수정
- 특정 근무지에 대한 컬러 반환 로직 구현
- 리스너 일부 버그 수정
> 근무지 삭제 버그 수정 / 리스너 버그 일부 수정 / 특정 근무지에 대한 컬러 값 불러오는 로직 구현

- Routory/Routory/Data/Services/EventService.swift
- Routory/Routory/Domain/Entities/CalendarEvent.swift
- Routory/Routory/Domain/Entities/WorkerDetail.swift
- Routory/Routory/Domain/Entities/Workplace.swift
- Routory/Routory/Presentation/Calendar/Model/CalendarModel.swift
- Routory/Routory/Presentation/Calendar/View/Cell/CalendarDayCell.swift
- Routory/Routory/Presentation/Calendar/View/Cell/EventCell.swift
- Routory/Routory/Presentation/Calendar/View/Components/CalendarEventVStackView.swift
- Routory/Routory/Presentation/Calendar/ViewController/CalendarViewController.swift
- Routory/Routory/Presentation/Calendar/ViewController/FilterViewController.swift
- Routory/Routory/Presentation/Calendar/ViewModel/CalendarViewModel.swift
- #138 
</br>
- 사장님 캘린더에서 근무 이벤트가 보이지 않는 현상 수정
- **사장님의 급여(0원)이 보이는 현상 수정 예정**
</br>
| 개인 캘린더 | <img src = "https://github.com/user-attachments/assets/077e2210-83eb-4936-8dc1-546169243986" width ="250"> |
| 공유 캘린더 | <img src = "https://github.com/user-attachments/assets/a08f9345-ebb6-447a-a17b-75cbd3bce5ca" width ="250"> |
</br>
> 사장님 캘린더에서 근무 안보이는 현상 수정

- Routory/Routory/Presentation/Registration/ShiftRegistration/Submodules/NewRoutine/ViewController/NewRoutineViewController.swift
- Routory/Routory/Presentation/Routine/ViewController/ManageRoutineViewController.swift
- Routory/Routory/Presentation/Routine/ViewController/WorkplaceRoutineViewController.swift
- #135 
</br>
- 전체 루틴 보기로 진입할 경우를 추가하고 내비게이션 헤더에 수정 버튼을 추가했습니다.
- 수정 버튼을 터치하면 .edit 모드로 변경되어 내용 수정가능합니다.
</br>
<video src="https://github.com/user-attachments/assets/9b828441-ff6a-4f4c-be99-8f80271b4573" controls width="480"></video>
> 전체 루틴 보기에서 루틴 수정하기

- Routory/Routory/Presentation/Home/ViewController/InviteCodeViewController.swift
- #148 
</br>
- 초대코드로 조회한 근무지의 id를 받아옵니다.
> workplaceId 실제 데이터 받아오기

- Routory/Routory/Data/Services/EventService.swift
- #157 
</br>
- Firebase에서 라벨 컬러 찾는 기능 비활성화
- 라벨 컬러를 설정하는 곳이 없어 nil처리 됨으로 인해 개인 근무가 보이지 않았음
</br>
> 초대받은 근무지에서 근무가 보이지 않는 현상 수정

- Routory/Routory/Presentation/Registration/ShiftRegistration/View/Components/WorkDateView.swift
> refactor: #155 - RepeatRow 숨김처리

- Routory/Routory/Presentation/Components/DeleteAlertViewController.swift
- Routory/Routory/Presentation/MyPage/ViewController/MyPageViewController.swift
Github Issue: #167
- #167 
</br>
| 로그아웃 확인 | <img src = "https://github.com/user-attachments/assets/23df2ea5-418e-4207-81b1-7adcd4231f55" width ="250"> |
</br>
> 로그아웃 확인 모달 구현

- Routory/Routory/Presentation/Home/ViewController/WorkplaceAddModalViewController.swift
- Routory/Routory/Presentation/MyPage/View/MyPageView.swift
- Routory/Routory/Presentation/Registration/Components/LabelView.swift
- Routory/Routory/Presentation/Registration/Components/SelectableListCell.swift
- Routory/Routory/Presentation/Registration/Components/SelectionViewController.swift
- Routory/Routory/Presentation/Registration/Components/TextInputViewController.swift
- Routory/Routory/Presentation/Registration/Components/ValueRowView.swift
- Routory/Routory/Presentation/Registration/Helpers/Helpers.swift
- Routory/Routory/Presentation/Registration/WorkplaceRegistration/Handler/WorkplaceRegistrationDelegateHandler.swift
- Routory/Routory/Presentation/Registration/WorkplaceRegistration/View/Components/SalaryInfoView.swift
- Routory/Routory/Presentation/Registration/WorkplaceRegistration/View/Components/WorkConditionView.swift
- Routory/Routory/Presentation/Registration/WorkplaceRegistration/View/Components/WorkplaceInfoView.swift
- Routory/Routory/Presentation/Registration/WorkplaceRegistration/View/WorkplaceRegistrationContentView.swift
- Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/WorkerWorkplaceRegistrationViewController.swift
- Routory/Routory/Resources/Assets.xcassets/Icons/Chevron/ChevronRightGray400.imageset/ChevronRightGray400.svg
- Routory/Routory/Resources/Assets.xcassets/Icons/Chevron/ChevronRightGray400.imageset/Contents.json
> 근무지 등록 UI 피그마와 비교 검토

- Routory/Routory/Presentation/Home/ViewController/HomeViewController.swift
- Routory/Routory/Presentation/Home/ViewController/WorkplaceAddModalViewController.swift
- 근무지 추가 모달 present와 dismiss에 애니메이션 적용했습니다.
> 근무지 추가 모달에 애니메이션 적용

- Routory/Routory/Data/Services/AppleAuthService.swift
- Routory/Routory/Data/Services/AuthService.swift
- #180 
</br>
- Apple로 로그인 후 탈퇴 시 토큰 무효화하는 기능 추가
</br>
> Apple 로그인 탈퇴 과정 수정

- MOUP/MOUP.xcodeproj/project.pbxproj
- MOUP/MOUP/Data/Services/EventService.swift
- MOUP/MOUP/Domain/Entities/Workplace.swift
- MOUP/MOUP/Presentation/Calendar/View/CalendarView.swift
- MOUP/MOUP/Presentation/Calendar/View/Cell/CalendarDayCell.swift
- MOUP/MOUP/Presentation/Calendar/View/Cell/EventCell.swift
- MOUP/MOUP/Presentation/Calendar/View/Components/CalendarEventVStackView.swift
- MOUP/MOUP/Presentation/Calendar/ViewController/CalendarEventListViewController.swift
- MOUP/MOUP/Presentation/Calendar/ViewController/CalendarViewController.swift
- MOUP/MOUP/Presentation/Calendar/ViewModel/CalendarViewModel.swift
- #193 
</br>
- 사장님 캘린더에서 근무 등록하기를 할수 없는 현상 수정
- 사장님 캘린더에서 셀의 이벤트 UI가 비정상적으로 표시되는 현상 수정
- 공유 캘린더 필터에서 최초값이 터치해야만 적용되는 현상 수정
- 캘린더 셀에서 근무 시간이 비정상적으로 계산되는 현상 수정
- 07:00 ~ 20:00 계산 시 캘린더 셀에서 1시간으로 표시됨
</br>
> 1.0.1 버전의 버그 수정
